---
- name: Actualizar el cache
  become: yes
  apt: update_cache=yes cache_valid_time=3600

- name: Instalar software requerido
  apt:
     name={{ item }}
     state=present
     update_cache=yes
  become: yes
  with_items:
    - apache2
    - mysql-server
    - php7.0
    - libapache2-mod-php7.0
    - php7.0-cli
    - php7.0-common
    - php7.0-gd
    - php7.0-xml
    - php7.0-mysql
    - python3-dev
    - python3-pip
    - python3-mysqldb
